language:
- python
python:
- 2.7
install:
#- sudo apt-get install gcc
#- wget ftp://ftp.astron.com/pub/file/file-5.12.tar.gz
#- tar xvfz file-5.12.tar.gz
#- cd file-5.12
#- ./configure --prefix ../local
#- make install
- sudo apt-get update
- sudo apt-get install libmagic-dev file
- pip install python-magic
script:
- python test.py


