language:
- python
python:
- 2.7
install:
- sudo apt-get install gcc
- wget ftp://ftp.astron.com/pub/file/file-5.12.tar.gz
- tar xvfz file-5.12.tar.gz
- cd file-5.12
- ./configure --prefix ~/virtualenv/python2.7
- make install
- pip install python-magic
- cd ..
script:
- file --mime-type data/word.doc
- python test.py


